apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-opa-deployment
  labels:
    app: oauth2-opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-opa
  template:
    metadata:
      labels:
        app: oauth2-opa
    spec:
      containers:
      - name: oauth2-opa
        image: oauth2-opa:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
