kind: Service
apiVersion: v1
metadata:
  name: oauth2-in-app-auth-deployment
  labels:
    app: oauth2-in-app-auth-deployment
spec:
  type: NodePort
  selector:
    app: oauth2-in-app-auth-deployment
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080      