kind: Service
apiVersion: v1
metadata:
  name: opa-ressource-server
  labels:
    app: opa-ressource-server
spec:
  type: NodePort
  selector:
    app: opa-ressource-server
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080      