spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/sample
          jwk-set-uri: http://localhost:9080/auth/realms/sample/protocol/openid-connect/certs