spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9080/auth/realms/Sample
          jwk-set-uri: http://keycloak:9080/auth/realms/sample/protocol/openid-connect/certs
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:      ddl-auto: create       
    