apiVersion: v1
kind: Pod
metadata:
  name: opa-ressource-server-one-pod
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: oauth2-opa
    image: oauth2-opa:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080    

  - name: opa
    image: openpolicyagent/opa:latest
    ports:
    - name: http
      containerPort: 8181
    args:
    - "run"
    - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
    - "--server"
    - "/policies"
    volumeMounts:
    - readOnly: true
      mountPath: /policies
      name: example-policy
  volumes:
  - name: example-policy
    configMap:
      name: example-policy
