apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-opa
  labels:
    app: oauth2-opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-opa
  template:
    metadata:
      labels:
        app: oauth2-opa
    spec:
      containers:
      - name: oauth2-opa
        image: oauth2-opa:latest
        imagePullPolicy: IfNotPresent
        ports:
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-opa
  labels:
    app: oauth2-opa
spec:
  type: LoadBalancer
  selector:
    app: oauth2-opa
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080                
