apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-in-app-auth
  labels:
    app: oauth2-in-app-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-in-app-auth
  template:
    metadata:
      labels:
        app: oauth2-in-app-auth
    spec:
      containers:
      - name: oauth2-in-app-auth
        image: oauth2-in-app-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-in-app-auth
  labels:
    app: oauth2-in-app-auth
spec:
  type: NodePort
  selector:
    app: oauth2-in-app-auth
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080                
