apiVersion: apps/v1
kind: Deployment
metadata:
  name: ressource-server-and-opa
  labels:
    app: ressource-server-and-opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ressource-server-and-opa
  template:
    metadata:
      labels:
        app: ressource-server-and-opa
      name: ressource-server-and-opa
    spec:
      containers:

      - name: opa
        image: openpolicyagent/opa:latest
        ports:
        - name: http
          containerPort: 8181
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/policies"
        volumeMounts:
        - readOnly: true
          mountPath: /policies
          name: example-policy
      volumes:
      - name: example-policy
        configMap:
          name: example-policy

      - name: ressource-server
        image: oauth2-opa:latest
        ports:
        - name: http
          containerPort: 8080          
---
kind: Service
apiVersion: v1
metadata:
  name: ressource-server-and-opa
  labels:
    app: ressource-server-and-opa
spec:
  type: NodePort
  selector:
    app: ressource-server-and-opa
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080                