kind: Service
apiVersion: v1
metadata:
  name: ressource-server-opa
  labels:
    app: ressource-server-opa
spec:
  type: NodePort
  selector:
    app: ressource-server-opa
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080        